# Generated by Django 5.0.6 on 2024-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_total_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.CharField(default='https://cdn4.iconfinder.com/data/icons/basic-ui-set-2-1/64/Basic_ui_2-16-1024.png', max_length=500),
        ),
    ]
